- name: install kube binaries
  hosts: all
  become: yes
  tasks:
    - include_tasks: bootstrap_ubuntu.yaml # Contains tasks bootstrap components for ubuntu systems
      when: ansible_distribution == "Ubuntu"

    - name: "Add gpg key (Ubuntu)"
      apt_key:
        url: https://pkgs.k8s.io/core:/stable:/v1.34/deb/Release.key
        state: present
        keyring: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      when: ansible_distribution == "Ubuntu"

    - name: "Add kubernetes source list (Ubuntu)"
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] https://pkgs.k8s.io/core:/stable:/v1.34/deb/ /"
        state: present
        filename: "kubernetes"
      when: ansible_distribution == "Ubuntu"

    - name: "Update the repository cache (Ubuntu)"
      apt:
        update_cache: yes
      when: ansible_distribution == "Ubuntu"

    - name: "Install kubelet, kubeadm, kubectl (Ubuntu)"
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - kubelet
        - kubeadm
        - kubectl
      when: ansible_distribution == "Ubuntu"